```{r}
library(dplyr)
library(emmeans)
library(car)
library(ggplot2)
```

```{r}
data <- read.csv('cartpole-pid/processed.csv')

model <- lm(dist ~ sample * group, data = data)
summary(model)
```
```{r}
ggplot(data, aes(x = sample, y = dist, shape = group, color = group)) + geom_point() +
  geom_smooth(method = lm, aes(fill = group))
```

```{r}
data <- read.csv('cartpole-dqn/processed.csv')

model <- lm(dist ~ sample * group, data = data)
summary(model)
```

```{r}
ggplot(data, aes(x = sample, y = dist, shape = group, color = group)) + geom_point() +
  geom_smooth(method = lm, aes(fill = group))
```


```{r}
data <- read.csv('lunar-lander-ppo/processed.csv')

model <- lm(dist ~ sample * group, data = data)
summary(model)
```

```{r}
ggplot(data, aes(x = sample, y = dist, shape = group, color = group)) + geom_point() +
  geom_smooth(method = lm, aes(fill = group))
```

```{r}
data <- read.csv('lunar-lander-lqr/processed.csv')

model <- lm(dist ~ sample * group, data = data)
summary(model)
```

```{r}
ggplot(data, aes(x = sample, y = dist, shape = group, color = group)) + geom_point() +
  geom_smooth(method = lm, aes(fill = group))
```
